// The join code, as a shape rather than as a string.
//
// One module because the value now crosses four places -- generated by the
// teacher route, typed on the login screen, looked up pre-auth, and enrolled
// post-auth in the OAuth callback -- and the generator and the validators must
// not be able to disagree about what a code is. CODE_ALPHABET used to be a
// private const inside app/api/teacher/classes/route.ts; it lives here now and
// that route imports it, so there is one alphabet, not two copies drifting.
//
// Imports nothing, so `node --test` can load it directly.

// The glyphs that survive being read off a projector and typed by hand: 0/O and
// 1/I/L are dropped because they get misread. 31 characters at length 6 is
// 887,503,681 combinations, which is the number the pre-auth rate limits in
// app/lib/rate-limit.ts are sized against.
//
// THIS IS A GENERATION POLICY, NOT A VALIDATION RULE, and the difference is not
// academic. Measured against production on 2026-08-21: of 7 active classes,
// THREE carry a join_code containing '0' or '1'. They predate this alphabet, and
// nothing ever migrated them.
//
// So validating a typed code against this set would tell the students of those
// three classes that their teacher's code is impossible, and refuse to even look
// it up -- a screen they could never get past. /api/enroll has always checked
// length alone, which is why the divergence has never bitten. checkJoinCode
// below does the same. The alphabet still governs what NEW codes are minted; it
// does not get to overrule what is already in the table.
export const CODE_ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
export const CODE_LENGTH = 6;

export type CodeReason = 'empty' | 'length';

// A flat record rather than a discriminated union on `ok`. tsconfig has
// strict:false, so strictNullChecks is off and TypeScript will not narrow a
// union on a literal boolean -- callers would get "Property 'reason' does not
// exist" inside an `if (!result.ok)` branch where it plainly does. One shape,
// always populated, works under the compiler this repo actually runs.
export interface CodeCheck {
  ok: boolean;
  /** The normalised code. Empty string when ok is false. */
  code: string;
  /** Why it was refused. Null when ok is true. */
  reason: CodeReason | null;
}

/**
 * Normalises and validates a typed code. Uppercases, and strips the spaces and
 * dashes people insert when copying a six-character string off a board.
 *
 * LENGTH ONLY, matching /api/enroll. A charset check against CODE_ALPHABET was
 * written first and removed: three live classes carry codes containing '0' or
 * '1', so it would have made them unjoinable. See the note on CODE_ALPHABET.
 *
 * The consequence, stated so it is a choice rather than an oversight: a mistyped
 * code now reaches the database and is charged against the miss rate limiter,
 * where a charset check would have caught it for free. At 30 misses per ten
 * minutes that is affordable, and a limit that occasionally costs a typo is far
 * better than a validator that locks real students out of real classes.
 */
export function checkJoinCode(raw: unknown): CodeCheck {
  const bad = (reason: CodeReason): CodeCheck => ({ ok: false, code: '', reason });
  if (typeof raw !== 'string') return bad('empty');
  const code = raw.replace(/[\s-]/g, '').toUpperCase();
  if (code.length === 0) return bad('empty');
  if (code.length !== CODE_LENGTH) return bad('length');
  return { ok: true, code, reason: null };
}

/** The client-side courtesy check: is the field ready to submit? */
export function isPlausibleJoinCode(raw: string): boolean {
  return checkJoinCode(raw).ok;
}

// ─── The cookie that carries the code through the OAuth round trip ───────────
//
// NOT THE `next` PARAM AND NOT ANY QUERY STRING, which is what this replaces.
// The old flow put the code in next=/dashboard?code=XXXXXX, so it travelled
// through Google's redirect in a URL: visible in browser history, in the
// Referer header, and in any log that records query strings, and editable by
// the person holding it. A cookie is none of those things.
//
// httpOnly so no script can read it back, Secure so it never crosses http
// (localhost is treated as a trustworthy origin by browsers, so this does not
// break local verification), SameSite=Lax so it DOES survive the top-level GET
// navigation back from accounts.google.com -- which is exactly the case Lax
// permits and Strict would break.
export const JOIN_COOKIE = 'um_join';

// Long enough for a slow Google account chooser and a password prompt, short
// enough that a code left in a browser is not a standing credential. The
// callback has to handle expiry as a real state either way, because a student
// who abandons the sign-in and comes back tomorrow will hit it.
export const JOIN_COOKIE_MAX_AGE = 15 * 60;

export const JOIN_COOKIE_OPTIONS = {
  httpOnly: true,
  secure: true,
  sameSite: 'lax',
  path: '/',
  maxAge: JOIN_COOKIE_MAX_AGE,
} as const;
