// The import attribute is required by Node's ESM loader, which is how the
// offline test suite loads this module. Next bundles the JSON either way.
import taxonomy from "../../data/docs/misconception_taxonomy.json" with { type: "json" };

// Human-readable labels for misconception slugs.
//
// WHY NOT STRIP LATEX FROM distractor_logic
//
// The build spec asked for `misconception_label` to be the distractor prose
// with LaTeX stripped, tested against real strings. Measuring the real strings
// is what changed the answer. Of the 4000 distractor_logic entries in the
// production bank, 2667 contain inline math and 720 contain \frac. Stripping
// that well is real work, and stripping it badly turns "$\frac{4}{5}$ = 80%"
// into "45 = 80%", which is worse than leaving it alone: a teacher reading a
// mangled fraction has been given a wrong number rather than a missing one.
//
// data/docs/misconception_taxonomy.json already carries a plain-English
// `definition` for every slug, written for exactly this purpose. Checked across
// all 480: zero contain a dollar sign, zero contain a backslash. So the label
// needs no stripping, and it is a definition of the misconception rather than
// one item's phrasing of it.
//
// Coverage was verified against the whole bank, not a sample: all 1124
// questions rows were paged and every one of the 475 distinct slugs in use
// resolves here. Five taxonomy slugs are unused, which is harmless.
//
// The raw prose is not discarded. It travels beside this as
// `misconception_label_raw`, which is the same representative string the
// dashboard card shows, so a teacher can still read the example their students
// actually hit.

type TaxonomyEntry = { slug: string; definition: string };

// Cast rather than let TypeScript infer a 480-entry literal type from the JSON.
// The inferred type is enormous, costs real time on every tsc run, and buys
// nothing: the file is generated by scripts/build_misconception_taxonomy.py and
// its shape is pinned by scripts/check_taxonomy_generated.py.
const ENTRIES = (taxonomy as { slugs: TaxonomyEntry[] }).slugs;

const DEFINITIONS: Map<string, string> = new Map(
  ENTRIES.map((entry) => [entry.slug, entry.definition])
);

/**
 * The readable label for a slug.
 *
 * FALLBACK IS THE SLUG ITSELF, never an empty cell. The realistic way to get
 * here is an item tagged with a new slug before the taxonomy is regenerated,
 * and a teacher reading `weights_swapped` has strictly more than a teacher
 * reading a blank. An empty cell also reads as "no misconception", which is a
 * different and wrong claim.
 */
export function misconceptionLabel(slug: string): string {
  return labelOrFallback(DEFINITIONS.get(slug), slug);
}

/**
 * The fallback decision on its own, exported so it can be tested.
 *
 * Split out because the whitespace branch is UNREACHABLE with the current
 * taxonomy: no entry has a blank definition, so a test driving
 * misconceptionLabel() cannot reach it, and fault injection confirmed that
 * deleting the trim check left every test green. A guard no test can fail is a
 * guard nobody can trust, so the decision is testable directly.
 */
export function labelOrFallback(definition: string | undefined, slug: string): string {
  if (definition && definition.trim().length > 0) return definition;
  return slug;
}

/** Exposed for the coverage test, which asserts against the real bank. */
export function knownSlugCount(): number {
  return DEFINITIONS.size;
}
